In [1]:
# numpy

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.zeros((2,3)) #creates array with 3 columns and 2 rows

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.random.random((2,3))

array([[0.12291566, 0.37971583, 0.47441926],
       [0.85847472, 0.67043908, 0.25463747]])

In [6]:
a = 1
a +=10
a

11

In [7]:
a3 = np.full((2,2),1) # to input specific value in the array
a3

array([[1, 1],
       [1, 1]])

In [8]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
np.arange(1,10,2) # its a*range not ar*range create array starting from 1 with a step count 2 

array([1, 3, 5, 7, 9])

In [10]:
np.linspace(5,20,5) # it forces to have 5 numbers automatically inside the array between the given numbers

array([ 5.  ,  8.75, 12.5 , 16.25, 20.  ])

In [11]:
a1 = np.arange(1,10,2)
a2 = np.arange(0,10,2)
a1,a2  # creates 2 dimensional array


(array([1, 3, 5, 7, 9]), array([0, 2, 4, 6, 8]))

In [12]:
a1.shape # tells that it is a 1 dim array with 5 values

(5,)

In [13]:
a3.size # gives size of the array

4

In [14]:
a3.ndim # gives dim of the array

2

In [15]:
a3.dtype # give the data type may be int32 or int64 or int128 same follows with the float

dtype('int64')

In [16]:
np.sum([10,20,30,40])

100

In [17]:
a4 = np.array([[1,2],[0,4]])
a4

array([[1, 2],
       [0, 4]])

In [18]:
np.sum([[1,2],[0,4]], axis=0) # axis = 0 adds coloumns

array([1, 6])

In [19]:
np.sum([[1,2],[0,4]], axis=1) # axis = 1 adds rows

array([3, 4])

In [20]:
np.exp(2) # exponential form , eulers numbers e to the power of 2

7.38905609893065

In [21]:
np.sqrt(9)

3.0

In [22]:
a=np.sqrt(10) # precision is changed to 2
str(round(a,2))

'3.16'

In [23]:
b=np.sqrt(10) # precision is changed to 6
str(round(b,6))

'3.162278'

In [24]:
# to change precision to 50 is it possible
# from decimal import Decimal
# decimal(50.0).sqrt(10)

In [25]:
np.sin(90)

0.8939966636005579

In [26]:
np.cos(0)

1.0

In [27]:
np.tan(45)

1.6197751905438615

In [28]:
a5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# to select from soemthing from the above array we have

In [30]:
l = [12,23,34]
l.append(45)  # appending an element

In [31]:
l

[12, 23, 34, 45]

In [32]:
a5[0] 

array([1, 2, 3])

In [33]:
a5[0][2] 

3

In [34]:
a5[0,2] # both are same to get an element from the list of arrays

3

In [35]:
# a5[rows,column] this is the basic syntax

In [36]:
a5[0:2,:2]

array([[1, 2],
       [4, 5]])

In [37]:
a5[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [38]:
# or
a5[1:,1:]

array([[5, 6],
       [8, 9]])

In [39]:
a5[1,0:2]

array([4, 5])

In [40]:
# for 2 seperate numbers we have fetch seperately


In [41]:
a = a5[1,0]
b = a5[2,1]
np.array([a,b])  # creating an array from already existing arrays

array([4, 8])

In [42]:
#or
a5[[1,2],[0,1]]

array([4, 8])

In [43]:
c = a + b

In [44]:
c

12

In [45]:
# pandas
# series, dataframes, panel data

In [46]:
import pandas as pd

In [47]:
pd.Series([12,23,45,567])

0     12
1     23
2     45
3    567
dtype: int64

In [48]:
pd.Series([12,33,45,567.34], index=['a','b','c','d'])

a     12.00
b     33.00
c     45.00
d    567.34
dtype: float64

In [49]:
# pandas is same as numpy but in more structured form with labels, rows and columns

In [50]:
s = pd.Series({'a':12,'b':23,'c':45})


In [51]:
s

a    12
b    23
c    45
dtype: int64

In [52]:
a = pd.Series([12,33,45,567.34], index=['a','b','c','d'])
b = pd.Series([12,33,45,567.34], index=['a','b','c','d'])
# to perform calculations indexes should match r else it wont match, it will show NANS.

In [53]:
c = a/b  
c

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [54]:
a = np.array([12,33,45,567.34])
b = np.array([12,33,45,567.34])

In [55]:
c = a/b  
c
# using numpy we can do the math 

array([1., 1., 1., 1.])

In [56]:
d = pd.Series({'a':12,'b':23,'c':45})
s = pd.Series(d)

In [57]:
s

a    12
b    23
c    45
dtype: int64

In [58]:
pd.DataFrame([[1,2,3],[4,5,6]])

0  1  2
0  1  2  3
1  4  5  6

In [59]:
pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=['A','B','C'])

A  B  C
a  1  2  3
b  4  5  6

In [60]:
#can you create data frame with a series object

In [61]:
df = pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=['A','B','C'])

In [62]:
df = pd.DataFrame({'Sl.No':[1,2,3,4], 'Names':['A','B','C','D']})

In [63]:
df

Sl.No Names
0      1     A
1      2     B
2      3     C
3      4     D

In [64]:
np.nan

nan

In [65]:
pd.DataFrame({'Sl.No':[1,2,3,4], 'Names':['A','B','C']})

ValueError: arrays must all be same length

In [66]:
#Check the error above 

In [67]:
df = pd.DataFrame({'Sl.No':[1,2,3,4], 'Names':['A','B','C','D']})

In [68]:
df

Sl.No Names
0      1     A
1      2     B
2      3     C
3      4     D

In [69]:
df['Sl.No']

0    1
1    2
2    3
3    4
Name: Sl.No, dtype: int64

In [70]:
type(df)

pandas.core.frame.DataFrame

In [71]:
type(df['Sl.No']) # type is series 

pandas.core.series.Series

In [72]:
df.shape

(4, 2)

In [73]:
df.size

8

In [74]:
df.Names # because its trying to find if dl is having Names

0    A
1    B
2    C
3    D
Name: Names, dtype: object

In [75]:
df.Sl.No # because its trying to find if dl is having and sl and also sl is having a attribute no in sl

AttributeError: 'DataFrame' object has no attribute 'Sl'

In [ ]:
df['Sl.No'] # this is the better way of doing it 

In [76]:
df = pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=['A','B','C'])

In [77]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]], index=['a','b'], columns=['A','B','C'])

In [78]:
df3 = df + df1

In [79]:
df3

A   B   C
a  2   4   6
b  8  10  12

In [80]:
# same as series if you have same coumns and indexes they can be addes r else it shows NAN.

In [81]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, a to b
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      int64
 1   B       2 non-null      int64
 2   C       2 non-null      int64
dtypes: int64(3)
memory usage: 64.0+ bytes


In [82]:
#slicing and dicing in 3D

In [83]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27]]])

In [84]:
a.ndim

3

In [85]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [86]:
a[1:2,1:]

array([], shape=(0, 8, 3), dtype=int64)

In [87]:
array1 = np.arange(27).reshape(3,3,3)

In [88]:
array1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
array1[2][0][1]

19

In [90]:
array1 = np.arange(18).reshape(3,2,3)

In [91]:
array1[2][0][1]

13

In [92]:
df1

A  B  C
a  1  2  3
b  4  5  6

In [93]:
a = np.random.rand(5,4)

In [94]:
a

array([[0.14359581, 0.0451232 , 0.4592911 , 0.23478853],
       [0.81958084, 0.91636718, 0.90497757, 0.5395941 ],
       [0.13506947, 0.57114046, 0.59855033, 0.18138132],
       [0.88480844, 0.94322931, 0.49008265, 0.75605758],
       [0.94808445, 0.3924389 , 0.97648608, 0.22296976]])

In [95]:
df = pd.DataFrame(a, index=["a","b","c","d","e"], columns=["A","B","C","D"])

In [96]:
df

A         B         C         D
a  0.143596  0.045123  0.459291  0.234789
b  0.819581  0.916367  0.904978  0.539594
c  0.135069  0.571140  0.598550  0.181381
d  0.884808  0.943229  0.490083  0.756058
e  0.948084  0.392439  0.976486  0.222970

In [97]:
df["C"]

a    0.459291
b    0.904978
c    0.598550
d    0.490083
e    0.976486
Name: C, dtype: float64

In [98]:
type(df["C"])

pandas.core.series.Series

In [99]:
df.rename(columns = {"C":"C1"}, inplace=True)

In [100]:
df

A         B        C1         D
a  0.143596  0.045123  0.459291  0.234789
b  0.819581  0.916367  0.904978  0.539594
c  0.135069  0.571140  0.598550  0.181381
d  0.884808  0.943229  0.490083  0.756058
e  0.948084  0.392439  0.976486  0.222970

In [101]:
df.rename(index = {"b":"b1"}, inplace=True)

In [102]:
df

A         B        C1         D
a   0.143596  0.045123  0.459291  0.234789
b1  0.819581  0.916367  0.904978  0.539594
c   0.135069  0.571140  0.598550  0.181381
d   0.884808  0.943229  0.490083  0.756058
e   0.948084  0.392439  0.976486  0.222970

In [103]:
#pandas data selection for rows : loc and iloc

In [104]:
df.loc["a"]

A     0.143596
B     0.045123
C1    0.459291
D     0.234789
Name: a, dtype: float64

In [105]:
df.loc["a":"e"]

A         B        C1         D
a   0.143596  0.045123  0.459291  0.234789
b1  0.819581  0.916367  0.904978  0.539594
c   0.135069  0.571140  0.598550  0.181381
d   0.884808  0.943229  0.490083  0.756058
e   0.948084  0.392439  0.976486  0.222970

In [106]:
df.loc["a","D"]

0.23478853414199463

In [107]:
df

A         B        C1         D
a   0.143596  0.045123  0.459291  0.234789
b1  0.819581  0.916367  0.904978  0.539594
c   0.135069  0.571140  0.598550  0.181381
d   0.884808  0.943229  0.490083  0.756058
e   0.948084  0.392439  0.976486  0.222970

In [108]:
#loc is used for integer r index location based indexing/selection by position

In [109]:
df.iloc[0]

A     0.143596
B     0.045123
C1    0.459291
D     0.234789
Name: a, dtype: float64

In [110]:
#iloc returns series for single row r column r dataframes for multiple rows r columns

In [111]:
df

A         B        C1         D
a   0.143596  0.045123  0.459291  0.234789
b1  0.819581  0.916367  0.904978  0.539594
c   0.135069  0.571140  0.598550  0.181381
d   0.884808  0.943229  0.490083  0.756058
e   0.948084  0.392439  0.976486  0.222970

In [112]:
df[1:3]

A         B        C1         D
b1  0.819581  0.916367  0.904978  0.539594
c   0.135069  0.571140  0.598550  0.181381

In [113]:
df.iloc[1:3,1:3]

B        C1
b1  0.916367  0.904978
c   0.571140  0.598550

In [114]:
#to make changes permanent alwasy use inplace = True

In [115]:
df.drop("B")  # drops the column 

KeyError: "['B'] not found in axis"

In [116]:
#error because we have included only 1 axis but our array is 2 dimensional

In [117]:
df.drop("B", axis =1) #  in pandas Ro x axis is 0 and y axis is 1 and vise versa in numpy

A        C1         D
a   0.143596  0.459291  0.234789
b1  0.819581  0.904978  0.539594
c   0.135069  0.598550  0.181381
d   0.884808  0.490083  0.756058
e   0.948084  0.976486  0.222970

In [118]:
df  # beacuse i have not included inplace it gives me back column B

A         B        C1         D
a   0.143596  0.045123  0.459291  0.234789
b1  0.819581  0.916367  0.904978  0.539594
c   0.135069  0.571140  0.598550  0.181381
d   0.884808  0.943229  0.490083  0.756058
e   0.948084  0.392439  0.976486  0.222970

In [119]:
df.drop("B", axis =1, inplace=True)

In [120]:
df

A        C1         D
a   0.143596  0.459291  0.234789
b1  0.819581  0.904978  0.539594
c   0.135069  0.598550  0.181381
d   0.884808  0.490083  0.756058
e   0.948084  0.976486  0.222970

In [121]:
df.drop("e", axis =0,inplace=True) # drops row

In [122]:
df

A        C1         D
a   0.143596  0.459291  0.234789
b1  0.819581  0.904978  0.539594
c   0.135069  0.598550  0.181381
d   0.884808  0.490083  0.756058

In [123]:
df.describe() # gives us the descriptive statistics

A        C1         D
count  4.000000  4.000000  4.000000
mean   0.495764  0.613225  0.427955
std    0.412446  0.203465  0.269708
min    0.135069  0.459291  0.181381
25%    0.141464  0.482385  0.221437
50%    0.481588  0.544316  0.387191
75%    0.835888  0.675157  0.593710
max    0.884808  0.904978  0.756058

In [124]:
#mean, median, mode, stddev, variance, kurtosis,skewness, IQR will be given by describe

In [125]:
df.mean()

A     0.495764
C1    0.613225
D     0.427955
dtype: float64

In [126]:
df["D"].median()

0.38719131472035495

In [127]:
df.mode()

A        C1         D
0  0.135069  0.459291  0.181381
1  0.143596  0.490083  0.234789
2  0.819581  0.598550  0.539594
3  0.884808  0.904978  0.756058

In [128]:
df.kurtosis()

A    -5.873222
C1    2.131415
D    -2.896129
dtype: float64

In [131]:
'''isntall mysql
conda install
at anaconda promt---conda prompt PyMySql'''

'isntall mysql\nconda install\nat anaconda promt---conda prompt PyMySql'

In [132]:
import pymysql

In [133]:
 df1 = pd.DataFrame([[1,2,np.nan,4],[5,6,7,np.nan],[9,np.nan,np.nan,4]],index = ["a","b","c"],columns =["c1","c2","c3","c4"])

In [134]:
df1

c1   c2   c3   c4
a   1  2.0  NaN  4.0
b   5  6.0  7.0  NaN
c   9  NaN  NaN  4.0

In [135]:
df1.isna() #Nan values: to check there presence, to removce r drop or to full the Nan values

c1     c2     c3     c4
a  False  False   True  False
b  False  False  False   True
c  False   True   True  False

In [136]:
df1.isna().sum() # sum of the true values column wise

c1    0
c2    1
c3    2
c4    1
dtype: int64

In [142]:
df1

c1   c2   c3   c4
a   1  2.0  NaN  4.0
b   5  6.0  7.0  NaN
c   9  4.0  NaN  4.0

In [143]:
df1["c2"].fillna(df1["c2"].mean(),inplace=True)

In [144]:
df1

c1   c2   c3   c4
a   1  2.0  NaN  4.0
b   5  6.0  7.0  NaN
c   9  4.0  NaN  4.0

In [145]:
# when not to fill values with mean?
# if the outlier is present in that column

In [146]:
# outlier is something in a data which is different compared to other values
# how to check the presence of outlier?
# By using box plots for that particular column 